server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Compression gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

    # Assets statiques — cache long
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    # API → proxy vers le back Spring Boot
    location /api/ {
        proxy_pass http://back:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Uploads/images → proxy vers le back
    location /uploads/ {
        proxy_pass http://back:8080;
        proxy_set_header Host $host;
    }

    # React Router — toutes les routes → index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}